### ISSUE TITLE
Make Blue work with Java 9

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#378]
Blue is having problems with Java 9 installations.  Look at adding module access where necessary, as referenced in Dave's message in https://github.com/kunstmusik/blue/issues/377

**Comment by kunstmusik** [comment]
Following up, I looked into this a bit and found that one of the libraries I use, ControlsFX, is only being distributed now either for Java 8 or 9 and it is mutually exclusive (the one for 8 only works on 8, etc.).  This prevents me from creating a Blue release that works with both Java 8 and 9 at this time.  For now, Blue will stay on Java 8 and this will be re-evaluated later.

**Comment by fcahoon** [comment]
I'm now running on a Linux machine with a HiDPI display, and the GUI looks bad (even with --fontsize set to something reasonable). I've read that using JDK 9 solves this problem automagically, although I have yet to see if this works myself. Can you give me some hints on how to build my own JDK 9 version so I can see if it fixes my GUI issues?

**Comment by kunstmusik** [comment]
Well the situation hasn't changed that ControlsFX only works with either Java 8 or Java 9.  I haven't tried since the last message here, but you could try to replace the controlsfx jar in the controls-fx module under the release folder with the Java 9 version.  After that, you could see if the build then works by loading the main blue application project in Netbeans and building it.

**Comment by kunstmusik** [comment]
Well the situation hasn't changed that ControlsFX only works with either Java 8 or Java 9.  I haven't tried since the last message here, but you could try to replace the controlsfx jar in the controls-fx module under the release folder with the Java 9 version.  After that, you could see if the build then works by loading the main blue application project in Netbeans and building it.

**Comment by fcahoon** [comment]
I believe I have built blue successfully using JDK 9 and controlsfx-9.0.0.jar, but I'm still getting this error: When I choose Tools->Options from the menu, no window pops up, but the following stack dump shows up in the blue application log window:


java.lang.ClassNotFoundException: javax.activation.DataContentHandlerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:197)
Caused: java.lang.ClassNotFoundException: javax.activation.DataContentHandlerFactory starting from ModuleCL@268370fb[org.openide.awt] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@1ed4004b, ModuleCL@23305a88[org.netbeans.api.annotations.common]]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:199)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
Caused: java.lang.NoClassDefFoundError: javax/activation/DataContentHandlerFactory
	at org.openide.awt.QuickSearch.setUpSearch(QuickSearch.java:346)
	at org.openide.awt.QuickSearch.<init>(QuickSearch.java:84)
	at org.openide.awt.QuickSearch.attach(QuickSearch.java:174)
	at org.openide.awt.QuickSearch.attach(QuickSearch.java:102)
	at org.netbeans.modules.options.OptionsPanel.initUI(OptionsPanel.java:362)
	at org.netbeans.modules.options.OptionsPanel.<init>(OptionsPanel.java:152)
	at org.netbeans.modules.options.OptionsDisplayerImpl.showOptionsDialog(OptionsDisplayerImpl.java:161)
	at org.netbeans.api.options.OptionsDisplayer$3.run(OptionsDisplayer.java:223)
	at org.netbeans.api.options.OptionsDisplayer$3.run(OptionsDisplayer.java:209)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:115)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:75)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71)
	at org.openide.util.Mutex.readAccess(Mutex.java:193)
	at org.netbeans.api.options.OptionsDisplayer.openImpl(OptionsDisplayer.java:209)
	at org.netbeans.api.options.OptionsDisplayer.open(OptionsDisplayer.java:156)
	at org.netbeans.api.options.OptionsDisplayer.open(OptionsDisplayer.java:106)
	at org.netbeans.api.options.OptionsDisplayer.open(OptionsDisplayer.java:172)
	at org.netbeans.modules.options.OptionsWindowAction.actionPerformed(OptionsWindowAction.java:39)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:174)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:70)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:91)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:74)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:177)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:980)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1024)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6578)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3343)
	at java.desktop/java.awt.Component.processEvent(Component.java:6343)
	at java.desktop/java.awt.Container.processEvent(Container.java:2259)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4961)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2317)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4539)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4480)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2303)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2758)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:99)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by kunstmusik** [comment]
Ugh, this looks like an issue with Netbeans 8.2. (and its related Rich
Client Platform libraries which Blue uses):

https://superuser.com/questions/1268662/netbeans-8-2-wont-install-due-not-finding-jdk

I think the Netbeans 8.2. RCP just isn't designed to work with Java 9, and
Netbeans 9 is undergoing a long transition from the ownership by Oracle to
Apache.

I'm going to have to do some research soon as the situation is a bit of a
mess.  Java 9 is out but breaks a lot of things; JavaFX is going to be no
longer provided as part of JDK after Java 11; etc.  I may have to do a
rewrite soon to deal with the way Java and Netbeans are evolving.

**Comment by fcahoon** [comment]
Ok, I'll back off on the hopes of that working for a while. I do have an alternative scaling technique using https://github.com/kaueraal/run_scaled which doesn't provide the crisp resolution but is quite usable.

**Comment by hajdam** [comment]
Just a note - I believe, that since Java 9, there is now possible to create multirelease jar files which could maybe solve your issue with different versions for ControlsFX.
Described for example here: https://www.javaworld.com/article/3184029/java-language/java-9s-other-new-enhancements-part-4-multi-release-jar-files.html

**Comment by kunstmusik** [comment]
@hajdam Thanks for this. I think there's still the bigger problem of what to do about Nebeans RCP and later Java.  If I have to require Java > 8 for updated Netbeans RCP, then it would also not be a problem to switch to Java 9-only Controls FX.  

I need time to experiment and research with newer Java releases (9,10, and 11...) and UI toolkit options (the standalone JavaFX for Java 11, LWJGL).  I suspect it will still be some time until I can figure out a good path forward.

**Comment by kunstmusik** [comment]
Blue 2.8.0 is updated to support Java 11+ (current LTS release as of this writing).
