### ISSUE TITLE
SSO: AL names is not always visible

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#483]
an AL but the name is not visible. Also cannot change or add AL points.
After restarting Blue and loading this same file, the AL names were there an i was able to edit them.

I've noticed that the Automation tab in the SSO is not always refreshed, perhaps this is the same issue
![Screenshot from 2019-11-27 09-34-04](https://user-images.githubusercontent.com/6670911/69750427-09099b80-114d-11ea-9f6e-af8865cb60eb.png)

 java.lang.NullPointerException
	at blue.soundObject.editor.sound.ParameterLineView.drawSelectedPoint(ParameterLineView.java:239)
	at blue.soundObject.editor.sound.ParameterLineView.repaint(ParameterLineView.java:160)
	at blue.soundObject.editor.sound.ParameterLineView.lambda$new$9(ParameterLineView.java:109)
	at blue.jfx.BlueFX.runOnFXThread(BlueFX.java:46)
	at blue.soundObject.editor.sound.ParameterLineView.lambda$new$10(ParameterLineView.java:108)
	at com.sun.javafx.binding.ListExpressionHelper$Generic.notifyListeners(ListExpressionHelper.java:593)
	at com.sun.javafx.binding.ListExpressionHelper$Generic.fireValueChangedEvent(ListExpressionHelper.java:571)
	at com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(ListExpressionHelper.java:109)
	at javafx.beans.property.ListPropertyBase.fireValueChangedEvent(ListPropertyBase.java:201)
	at javafx.beans.property.ListPropertyBase.lambda$new$0(ListPropertyBase.java:57)
[catch] at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at javafx.beans.binding.ListExpression.add(ListExpression.java:250)
	at blue.soundObject.editor.SoundEditor.lambda$editScoreObject$6(SoundEditor.java:261)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

Closing the project and re-opening it does not solve the issue. Only a complete restart of the program does

**Comment by tjingboem** [comment]
with the renewed AL system in the SSOs, i did not encounter this issue.
So i'll close this one.
