### ISSUE TITLE
blue won't launch

### ISSUE THREAD

**Issue by dougboblas** [kunstmusik/blue#486]
Mac Pro (late 2013), 3 GHz 8-Core Intel Xeon E5, 16 GB 1866 MHz DDR3
Mac OS Sierra 10.12.6

I am brand new to Blue. 
I downloaded blue_OSX_2.7.4 from the download page. I first mistakenly downloaded and installed JDK 13 which displayed lots of errors when I tried to launch Blue.
Then I downloaded and installed JDK 8 Update 231 (the only JDK 8 I could find) When I try to launch Blue, I get a large empty blue screen. The JDK files were downloaded from the referenced Oracle page. At the bottom is a very tiny red icon. I hit that and this bunch of error messages was displayed as follows --

java.lang.ClassNotFoundException: javafx.beans.property.BooleanProperty
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:197)
Caused: java.lang.ClassNotFoundException: javafx.beans.property.BooleanProperty starting from ModuleCL@3c4acee6[com.kunstmusik.blue] with possible defining loaders null and declared parents [ModuleCL@4ec6949c[electric.xml], ModuleCL@417a924a[blue.utilities], org.netbeans.JarClassLoader@2f679af0, ModuleCL@720432b9[blue.jfx], ModuleCL@67257623[blue.plugin], ModuleCL@28cb408b[org.apache.commons.lang3], ModuleCL@183673d4[jython], ModuleCL@10e1fad5[de.congrace.exp4j]]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:199)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Caused: java.lang.NoClassDefFoundError: javafx/beans/property/BooleanProperty
	at blue.mixer.Channel.<init>(Channel.java:88)
	at blue.mixer.Mixer.<init>(Mixer.java:63)
	at blue.BlueData.<init>(BlueData.java:91)
	at blue.projects.BlueProjectManager.createNewProject(BlueProjectManager.java:101)
	at blue.projects.BlueProjectManager.<init>(BlueProjectManager.java:84)
	at blue.projects.BlueProjectManager.getInstance(BlueProjectManager.java:78)
	at blue.ui.core.project.CurrentProjectsAction.getMenuPresenters(CurrentProjectsAction.java:55)
	at org.openide.awt.DynaMenuModel.loadSubmenu(DynaMenuModel.java:84)
	at org.openide.awt.MenuBar$LazyMenu$MenuFolder.createInstance(MenuBar.java:850)
	at org.openide.loaders.FolderInstance.defaultProcessObjectsFinal(FolderInstance.java:863)
	at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:705)
	at org.openide.util.Task.run(Task.java:232)
[catch] at org.netbeans.modules.openide.loaders.AWTTask.run(AWTTask.java:54)
	at org.netbeans.modules.openide.loaders.AWTTask$Processor.run(AWTTask.java:147)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Any assistance would be greatly appreciated.

**Comment by dougboblas** [comment]
I fixed the problem by removing JDK 13

**Comment by kunstmusik** [comment]
Glad that's worked out! The next version of Blue works with JDK 11+ and will hopefully be out in the next few weeks.  Will close this out.
