### ISSUE TITLE
Compiled blue, but no sound

### ISSUE THREAD

**Issue by muziker** [kunstmusik/blue#594]
I've compiled 2.8.1-12-g3716d698. When running it, the terminal shows: 

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory to field java.net.URL.handler

Loading up an example blue project like tutuwun or distantStars, and hitting the play button, i get "[Error ] Score generation failed" in the lower status bar. Using "view application log" i get this:

`
java.lang.RuntimeException: blue.soundObject.SoundObjectException: There was an score generation error in the soundObject:
Type: PolyObjectName: root
Start Time: 0
Cause:
Error in SoundLayer: 
Cause:
There was an score generation error in the soundObject:
Type: PythonObjectName: i1 - 8.07
Start Time: 34
Details:
Jython Error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'statement' is not defined
	at blue.ui.core.render.CSDRender.generateCSDImpl(CSDRender.java:249)
	at blue.services.render.CSDRenderService.generateCSD(CSDRenderService.java:44)
	at blue.csnd6.render.CS6RealtimeRenderService.render(CS6RealtimeRenderService.java:199)
	at blue.ui.core.render.RealtimeRenderManager.renderProject(RealtimeRenderManager.java:151)
	at blue.ui.core.render.RealtimeRenderManager.renderProject(RealtimeRenderManager.java:117)
	at blue.MainToolBar.renderProject(MainToolBar.java:338)
	at blue.MainToolBar.lambda$new$1(MainToolBar.java:149)
`

The preferences have been set to use Jack. Another csound based project, cabbage, works fine. On another note, on startup, the output pane does not show anything, and i had to use View->blue application log, to see this error pop up. Is this supposed to work this way?

**Comment by muziker** [comment]
I've tried setting PYTHONPATH to add the pythonLib as part of the module search path, and with a randomly chosen piece centaur-pelog_cloud_study.blue, clicking a pythonobject in the timeline opens up the code in the scoreobject editor. Pressing the Test button generates a valid score. Without a valid pythonpath, this does not work.

With distantstars, the pythonobject doesn't generate any score. Also looking through the python library shows that the score generation in this piece is using the 'statement' function, that doesn't seem to exist in the library any longer.

**Comment by kunstmusik** [comment]
Ah I wouldn't use PYTHONPATH point to a native python folder. I think the issue is that Distant Stars in the repo seems to have it's start time set to beyond the Setup object at time 0 in the 1st layer which has the statement() function defined.  I probably wrote this project before "Process on Load" was introduced so it would require it to be evaluated at least once before running the project.  If you rewind the play time to the beginning then render it should run.  I did not have a problem running Brian Wong's Tutunwun here however. 

Could you try the rewind and play for Distant Stars and confirm that works there for you?  Also, I will update the project in the repository to have process on load set so that object has its contents load when the project loads.

**Comment by muziker** [comment]
Whyso not with PYTHONPATH? Unless the python libraries are installed into a python search path, the program cannot load the python library. Or maybe the way i'm starting blue is wrong. I usually cd to <src directory>/application/target/blue/bin and start blue from there.

**Comment by kunstmusik** [comment]
Blue uses Jython (a Java version of Python) for its PythonObject which has
its own version of the Python standard libraries included. Using a native
version of Python's standar library is going to be out of sync with
Jython's and can confuse things. That said, I'm not sure the recent
versions of Jython use the PYTHONPATH environment variable.

As mentioned in the previous statement, I don't believe the problem on your
system with Distant Stars is related to python system libraries at all as
the statement() function was one that's defined in the project itself. You
should be able to run the examples/scripting/feldman.blue example which
also uses PythonObjects.

**Comment by muziker** [comment]
Right Jython, i saw that while blue was compiling. But jython itself doesn't seem to search for the library packages in /blue/application/target/blue/blue/pythonLib, which is why i had to add this to the pythonpath. 
The other things i had to do to get audio working was to change the Tools->Options->RealTime Render->Audio Out to point to the correct jack client, which in my case was an EQ. Quotes are necessary in this case because the jack client name has spaces in them. 

And I had to alter the -B hardware buffer settings to 1200 because rtaudio was complaining the -B setting was too low. The -B buffer size seems to be dependent on the size of the software buffer -b. Not too sure what the optimum is supposed to be though.

**Comment by tjingboem** [comment]
_And I had to alter the -B hardware buffer settings to 1200 because rtaudio was complaining the -B setting was too low. The -B buffer size seems to be dependent on the size of the software buffer -b. Not too sure what the optimum is supposed to be though._

Running Linux and Jack here- i might be mistaken, but isn't the Jack program responsible for the right Buffer settings?
I did not check those buffer settings.
![Screenshot from 2021-04-06 11-12-34](https://user-images.githubusercontent.com/6670911/113687944-20558300-96c9-11eb-88ab-c5852a297437.png)

**Comment by muziker** [comment]
Yes, but when i run this without the setting the hard/soft buffer, i get an error message that says the hardware buffer is not large enough. At the same time, i have to change the sample rate of any project that is being run to be the same as the jack sample rate. There's also this small user experience thing, when i change the buffer sizes, if the checkbox isn't ticked, the "apply" button is not highlighted, when really the "apply/save" settings button should change for anything that has been altered. 

Shouldn't the audio out setting be the jack client name for audio output? Like system_playback_ rather than just dac ?
