### ISSUE TITLE
windows 11 ENTERPRISE  8 gb RAM

### ISSUE THREAD

**Issue by aldoeri** [kunstmusik/blue#699]
it inicialice but it dosent open i have download also the open java and it dosent open 
C:\Users\Usuario\Downloads\BLUE-W~1.1\blue\bin>blue64

C:\Users\Usuario\Downloads\BLUE-W~1.1\blue\bin>

The launcher has determined that the parent process has a console and will reuse it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.
jul. 12, 2022 12:26:05 P. M. org.netbeans.ProxyURLStreamHandlerFactory register
SEVERE: No way to find original stream handler for jar protocol
java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.net.URLStreamHandler java.net.URL.handler accessible: module java.base does not "opens java.net" to unnamed module @6d03e736
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
        at org.netbeans.ProxyURLStreamHandlerFactory.register(ProxyURLStreamHandlerFactory.java:59)
        at org.netbeans.JarClassLoader.<clinit>(JarClassLoader.java:117)
        at org.netbeans.MainImpl.execute(MainImpl.java:153)
        at org.netbeans.MainImpl.main(MainImpl.java:60)
        at org.netbeans.Main.main(Main.java:58)

[blue] - initialization

program root directory: C:\Users\Usuario\Downloads\BLUE-W~1.1\blue
user configuration directory: C:\Users\Usuario\.blue

> loading classes from registry
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:416)
        at org.netbeans.TopSecurityManager.install(TopSecurityManager.java:525)
        at org.netbeans.core.NbLifecycleManager.advancePolicy(NbLifecycleManager.java:69)
        at org.netbeans.core.GuiRunLevel.run(GuiRunLevel.java:84)
        at org.netbeans.core.startup.Main.start(Main.java:295)
        at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by kunstmusik** [comment]
Closing as this was addressed off-tracker by using the latest dev build.
